---
title: " Biden Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill 
    theme: cerulean
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(scales)
library(gt)
library(kableExtra)
options(dplyr.summarise.inform = FALSE)
source("03_compare_current_with_previous.R")
```

Agency Review Teams Highlights
=====================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Current Additions to Agency Review Teams

```{r}
newnames <- anti_join(transition_data_current, transition_data_previous, by = "idstring")

newnames%>%
  knitr::kable() %>%
  kable_classic() %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "center", font_size = 12, fixed_thead = T) %>%
  row_spec(0, bold = T, color = "blue", font_size = 15) %>%
  column_spec(2, bold = T)

```

### Aggregate Team Changes

```{r}
agencycount_new = agencycount_current
just_change <- agencycount_compare %>% pull(change)
agencycount_new["change"] <- just_change

agencycount_new %>%
  filter(change > 0) %>%
knitr::kable() %>%
  kable_classic() %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "center", font_size = 12, fixed_thead = T) %>%
  row_spec(0, bold = T, color = "blue", font_size = 15) %>%
  column_spec(2, bold = T)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Top 10 Largest Agency Review Teams

```{r}
agencycount_largest <- agencycount_current %>%
  arrange(desc(current_count)) %>%
  slice(1:10)

agencycount_largest %>%
   knitr::kable(caption = "Largest Agency Review Teams") %>%
  kable_classic() %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "center", font_size = 12) %>%
  row_spec(0, bold = T, color = "blue", font_size = 15)
```

### Top 10 Smallest Agency Review Teams

```{r}
agencycount_smallest <- agencycount_current %>%
  arrange(current_count) %>%
  filter(current_count < 5)

agencycount_smallest %>%
   knitr::kable(caption = "Smallest Agency Review Teams") %>%
  kable_classic() %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "center", font_size = 12) %>%
  row_spec(0, bold = T, color = "blue", font_size = 15)

```

